<?php
return [
    'win_function' => 'shishicai',
    'bet_places'   => [
        //万千
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_wq_drg',
            'group' => 'lhd',
            'child' => '万千',
            'name'  => '万千-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_wq_tig',
            'group' => 'lhd',
            'child' => '万千',
            'name'  => '万千-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_wq_pea',
            'group' => 'lhd',
            'child' => '万千',
            'name'  => '万千-和',
        ],

        //万百
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_wb_drg',
            'group' => 'lhd',
            'child' => '万百',
            'name'  => '万百-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_wb_tig',
            'group' => 'lhd',
            'child' => '万百',
            'name'  => '万百-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_wb_pea',
            'group' => 'lhd',
            'child' => '万百',
            'name'  => '万百-和',
        ],
        //万十
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_ws_drg',
            'group' => 'lhd',
            'child' => '万十',
            'name'  => '万十-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_ws_tig',
            'group' => 'lhd',
            'child' => '万十',
            'name'  => '万十-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_ws_pea',
            'group' => 'lhd',
            'child' => '万十',
            'name'  => '万十-和',
        ],

        //万个
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_wg_drg',
            'group' => 'lhd',
            'child' => '万个',
            'name'  => '万个-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_wg_tig',
            'group' => 'lhd',
            'child' => '万个',
            'name'  => '万个-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_wg_pea',
            'group' => 'lhd',
            'child' => '万个',
            'name'  => '万个-和',
        ],

        //千百
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_qb_drg',
            'group' => 'lhd',
            'child' => '千百',
            'name'  => '千百-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_qb_tig',
            'group' => 'lhd',
            'child' => '千百',
            'name'  => '千百-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_qb_pea',
            'group' => 'lhd',
            'child' => '千百',
            'name'  => '千百-和',
        ],

        //千十
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_qs_drg',
            'group' => 'lhd',
            'child' => '千十',
            'name'  => '千十-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_qs_tig',
            'group' => 'lhd',
            'child' => '千十',
            'name'  => '千十-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_qs_pea',
            'group' => 'lhd',
            'child' => '千十',
            'name'  => '千十-和',
        ],

        //千个
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_qg_drg',
            'group' => 'lhd',
            'child' => '千个',
            'name'  => '千个-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_qg_tig',
            'group' => 'lhd',
            'child' => '千个',
            'name'  => '千个-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_qg_pea',
            'group' => 'lhd',
            'child' => '千个',
            'name'  => '千个-和',
        ],

        //百十
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_bs_drg',
            'group' => 'lhd',
            'child' => '百十',
            'name'  => '百十-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_bs_tig',
            'group' => 'lhd',
            'child' => '百十',
            'name'  => '百十-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_bs_pea',
            'group' => 'lhd',
            'child' => '百十',
            'name'  => '百十-和',
        ],

        //百个
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_bg_drg',
            'group' => 'lhd',
            'child' => '百个',
            'name'  => '百个-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_bg_tig',
            'group' => 'lhd',
            'child' => '百个',
            'name'  => '百个-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_bg_pea',
            'group' => 'lhd',
            'child' => '百个',
            'name'  => '百个-和',
        ],

        //十个
        [
            '_name' => '龙',
            'odds'  => '2.177',
            'place' => 'lhd_sg_drg',
            'group' => 'lhd',
            'child' => '十个',
            'name'  => '十个-龙',
        ],
        [
            '_name' => '虎',
            'odds'  => '2.177',
            'place' => 'lhd_sg_tig',
            'group' => 'lhd',
            'child' => '十个',
            'name'  => '十个-虎',
        ],
        [
            '_name' => '和',
            'odds'  => '9.800',
            'place' => 'lhd_sg_pea',
            'group' => 'lhd',
            'child' => '十个',
            'name'  => '十个-和',
        ],

        //这里开始 是双面盘

        //总和
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_he_big',
            'group' => 'smp',
            'child' => '总和',
            'name'  => '总和-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_he_sml',
            'group' => 'smp',
            'child' => '总和',
            'name'  => '总和-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_he_sig',
            'group' => 'smp',
            'child' => '总和',
            'name'  => '总和-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_he_dob',
            'group' => 'smp',
            'child' => '总和',
            'name'  => '总和-双',
        ],

        //万位
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_01_big',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_01_sml',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_01_sig',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_01_dob',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-双',
        ],
        [
            '_name' => '质',
            'odds'  => '1.960',
            'place' => 'smp_01_qua',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-质',
        ],
        [
            '_name' => '合',
            'odds'  => '1.960',
            'place' => 'smp_01_clo',
            'group' => 'smp',
            'child' => '万位',
            'name'  => '万位-合',
        ],

        //千位
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_02_big',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_02_sml',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_02_sig',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_02_dob',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-双',
        ],
        [
            '_name' => '质',
            'odds'  => '1.960',
            'place' => 'smp_02_qua',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-质',
        ],
        [
            '_name' => '合',
            'odds'  => '1.960',
            'place' => 'smp_02_clo',
            'group' => 'smp',
            'child' => '千位',
            'name'  => '千位-合',
        ],

        //百位
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_03_big',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_03_sml',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_03_sig',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_03_dob',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-双',
        ],
        [
            '_name' => '质',
            'odds'  => '1.960',
            'place' => 'smp_03_qua',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-质',
        ],
        [
            '_name' => '合',
            'odds'  => '1.960',
            'place' => 'smp_03_clo',
            'group' => 'smp',
            'child' => '百位',
            'name'  => '百位-合',
        ],

        //十位
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_04_big',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_04_sml',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_04_sig',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_04_dob',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-双',
        ],
        [
            '_name' => '质',
            'odds'  => '1.960',
            'place' => 'smp_04_qua',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-质',
        ],
        [
            '_name' => '合',
            'odds'  => '1.960',
            'place' => 'smp_04_clo',
            'group' => 'smp',
            'child' => '十位',
            'name'  => '十位-合',
        ],

        //个位
        [
            '_name' => '大',
            'odds'  => '1.960',
            'place' => 'smp_05_big',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-大',
        ],
        [
            '_name' => '小',
            'odds'  => '1.960',
            'place' => 'smp_05_sml',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-小',
        ],
        [
            '_name' => '单',
            'odds'  => '1.960',
            'place' => 'smp_05_sig',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-单',
        ],
        [
            '_name' => '双',
            'odds'  => '1.960',
            'place' => 'smp_05_dob',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-双',
        ],
        [
            '_name' => '质',
            'odds'  => '1.960',
            'place' => 'smp_05_qua',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-质',
        ],
        [
            '_name' => '合',
            'odds'  => '1.960',
            'place' => 'smp_05_clo',
            'group' => 'smp',
            'child' => '个位',
            'name'  => '个位-合',
        ],
    ],
];
